template: testify
filename: "{{.InterfaceName | camelcase | firstLower }}_mock.go"
packages:
  github.com/zilliztech/milvus-backup/internal/taskmgr:
    interfaces:
      RestoreCollTaskView:
      RestoreTaskView:

  github.com/zilliztech/milvus-backup/core/client/milvus:
    interfaces:
      Grpc:
      Manage:

  github.com/zilliztech/milvus-backup/internal/storage:
    interfaces:
      Client:

  github.com/zilliztech/milvus-backup/core/restore:
    interfaces:
      CollMapper:
